package cz.tpsoft.tablesoccer.data.model;
// Generated 14.12.2012 13:40:40 by Hibernate Tools 3.2.1.GA



/**
 * GamePlayerId generated by hbm2java
 */
public class GamePlayerId  implements java.io.Serializable {


     private int gameId;
     private int playerId;

    public GamePlayerId() {
    }

    public GamePlayerId(int gameId, int playerId) {
       this.gameId = gameId;
       this.playerId = playerId;
    }
   
    public int getGameId() {
        return this.gameId;
    }
    
    public void setGameId(int gameId) {
        this.gameId = gameId;
    }
    public int getPlayerId() {
        return this.playerId;
    }
    
    public void setPlayerId(int playerId) {
        this.playerId = playerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GamePlayerId) ) return false;
		 GamePlayerId castOther = ( GamePlayerId ) other; 
         
		 return (this.getGameId()==castOther.getGameId())
 && (this.getPlayerId()==castOther.getPlayerId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGameId();
         result = 37 * result + this.getPlayerId();
         return result;
   }   


}


