package cz.tpsoft.tablesoccer.data.model;
// Generated 14.12.2012 13:40:40 by Hibernate Tools 3.2.1.GA



/**
 * GamePlayer generated by hbm2java
 */
public class GamePlayer  implements java.io.Serializable {


     private GamePlayerId id;

    public GamePlayer() {
    }

    public GamePlayer(GamePlayerId id) {
       this.id = id;
    }
   
    public GamePlayerId getId() {
        return this.id;
    }
    
    public void setId(GamePlayerId id) {
        this.id = id;
    }




}


