package cz.tpsoft.tablesoccer.data.model;
// Generated 14.12.2012 13:40:40 by Hibernate Tools 3.2.1.GA



/**
 * Game generated by hbm2java
 */
public class Game  implements java.io.Serializable {


     private int id;
     private int number;
     private int type;
     private Integer homeScore;
     private Integer awayScore;
     private int matchId;

    public Game() {
    }

	
    public Game(int id, int number, int type, int matchId) {
        this.id = id;
        this.number = number;
        this.type = type;
        this.matchId = matchId;
    }
    public Game(int id, int number, int type, Integer homeScore, Integer awayScore, int matchId) {
       this.id = id;
       this.number = number;
       this.type = type;
       this.homeScore = homeScore;
       this.awayScore = awayScore;
       this.matchId = matchId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Integer getHomeScore() {
        return this.homeScore;
    }
    
    public void setHomeScore(Integer homeScore) {
        this.homeScore = homeScore;
    }
    public Integer getAwayScore() {
        return this.awayScore;
    }
    
    public void setAwayScore(Integer awayScore) {
        this.awayScore = awayScore;
    }
    public int getMatchId() {
        return this.matchId;
    }
    
    public void setMatchId(int matchId) {
        this.matchId = matchId;
    }




}


