package cz.tpsoft.tablesoccer.data.model;
// Generated 14.12.2012 13:40:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * League generated by hbm2java
 */
public class League  implements java.io.Serializable {


     private int id;
     private String name;
     private String shortcut;
     private int level;
     private int division;
     private Set teams = new HashSet(0);

    public League() {
    }

	
    public League(int id, String name, String shortcut, int level, int division) {
        this.id = id;
        this.name = name;
        this.shortcut = shortcut;
        this.level = level;
        this.division = division;
    }
    public League(int id, String name, String shortcut, int level, int division, Set teams) {
       this.id = id;
       this.name = name;
       this.shortcut = shortcut;
       this.level = level;
       this.division = division;
       this.teams = teams;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShortcut() {
        return this.shortcut;
    }
    
    public void setShortcut(String shortcut) {
        this.shortcut = shortcut;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public int getDivision() {
        return this.division;
    }
    
    public void setDivision(int division) {
        this.division = division;
    }
    public Set getTeams() {
        return this.teams;
    }
    
    public void setTeams(Set teams) {
        this.teams = teams;
    }




}


