package cz.tpsoft.tablesoccer.data.model;
// Generated 14.12.2012 13:40:40 by Hibernate Tools 3.2.1.GA



/**
 * Player generated by hbm2java
 */
public class Player  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String secondName;
     private String nickName;
     private String teamId;

    public Player() {
    }

	
    public Player(int id) {
        this.id = id;
    }
    public Player(int id, String firstName, String secondName, String nickName, String teamId) {
       this.id = id;
       this.firstName = firstName;
       this.secondName = secondName;
       this.nickName = nickName;
       this.teamId = teamId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getSecondName() {
        return this.secondName;
    }
    
    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public String getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(String teamId) {
        this.teamId = teamId;
    }




}


