package cz.tpsoft.tablesoccer.data.model;
// Generated 14.12.2012 13:40:40 by Hibernate Tools 3.2.1.GA



/**
 * Team generated by hbm2java
 */
public class Team  implements java.io.Serializable {


     private int id;
     private League league;
     private String name;
     private String shortcut;

    public Team() {
    }

	
    public Team(int id, String name, String shortcut) {
        this.id = id;
        this.name = name;
        this.shortcut = shortcut;
    }
    public Team(int id, League league, String name, String shortcut) {
       this.id = id;
       this.league = league;
       this.name = name;
       this.shortcut = shortcut;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public League getLeague() {
        return this.league;
    }
    
    public void setLeague(League league) {
        this.league = league;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShortcut() {
        return this.shortcut;
    }
    
    public void setShortcut(String shortcut) {
        this.shortcut = shortcut;
    }




}


